# object detector boot.py
# generated by maixhub.com
from fpioa_manager import fm
from machine import UART
import sensor, image, lcd, time
import KPU as kpu
import gc, sys
import math
import ustruct
from struct import pack,unpack
fm.register(10, fm.fpioa.UART1_TX, force=True)
fm.register(11, fm.fpioa.UART1_RX, force=True)

uart = UART(UART.UART1, 9600, 8, 1, 0, timeout=1000, read_buf_len=4096)
def pixwl_to_realty(cx,cy):
    y2=0.0027*cx-0.0592*cy+26.39
    x2=0.0565*cx-0.0014*cy-10.0559
    x2=x2/100
    y2=y2/100
    return x2,y2
def recive_data():
    global uart
    global tmp_data
    if uart.any():
        tmp_data = uart.readline()
        print(temp_data)
        print("OK")
def distancen(blobn):
    wincx=160
    wincy=120
    x=blobn.x()
    y=blobn.y()
    return   math.sqrt(math.pow(wincx-x,2)+math.pow(wincy-y,2))
def compareblobs(blob1,blob2):
    temp=distancen(blob1)-distancen(blob2)
    if temp>0:
        return 1
    elif temp<0:
        return -1
    else:
        return 0
rechar=0x00
rechar1=0x00
rechar2=0x00
sendbuff=[0]*5;
center_Roi=[0,0,224,224]
thresholds = [

(38, 78, 19, 43, -63, 54)

             ]
def lcd_show_except(e):
    import uio
    err_str = uio.StringIO()
    sys.print_exception(e, err_str)
    err_str = err_str.getvalue()
    img = image.Image(size=(224,224))
    img.draw_string(0, 10, err_str, scale=1, color=(0xff,0x00,0x00))
    lcd.display(img)

def main(anchors, labels = None, model_addr="/sd/m.kmodel", sensor_window=(224, 224), lcd_rotation=2, sensor_hmirror=True, sensor_vflip=True):
    sensor.reset()
    sensor.set_pixformat(sensor.RGB565)
    sensor.set_framesize(sensor.QVGA)
    sensor.set_windowing(sensor_window)
    sensor.set_hmirror(sensor_hmirror)
    sensor.set_vflip(sensor_vflip)
    sensor.run(1)

    lcd.init(type=1)
    lcd.rotation(lcd_rotation)
    lcd.clear(lcd.WHITE)

    if not labels:
        with open('labels.txt','r') as f:
            exec(f.read())
    if not labels:
        print("no labels.txt")
        img = image.Image(size=(320, 240))
        img.draw_string(90, 110, "no labels.txt", color=(255, 0, 0), scale=2)
        lcd.display(img)
        return 1
    try:
        img = image.Image("startup.jpg")
        lcd.display(img)
    except Exception:
        img = image.Image(size=(320, 240))
        img.draw_string(90, 110, "loading model...", color=(255, 255, 255), scale=2)
        lcd.display(img)

    try:
        task = None
        task = kpu.load(model_addr)
        kpu.init_yolo2(task, 0.5, 0.3, 5, anchors) # threshold:[0,1], nms_value: [0, 1]
        while(True):
            img = sensor.snapshot()
            t = time.ticks_ms()
            nearblob=None

            try:
                objects = kpu.run_yolo2(task, img)
            except Exception as e:
                print(e)
            t = time.ticks_ms() - t
            if objects:
                print(objects)
                nearblob=objects[0]
                for obj in objects:
                    pos = obj.rect()
                    if compareblobs(nearblob,obj)==1:
                        nearblob = obj
                    img.draw_rectangle(pos)
                    img.draw_string(pos[0], pos[1], "%s : %.2f" %(labels[obj.classid()], obj.value()), scale=2, color=(255, 0, 0))



                    nearpos = nearblob.rect()
                    print(nearpos[0]+nearpos[2]/2,nearpos[1]+nearpos[3]/2)
                    a= pixwl_to_realty(nearpos[0]+nearpos[2]/2,(nearpos[1]+nearpos[3]/2))
                    x_a = a[0]-0.03
                    Y_a = a[1]+0.015
                    out_str="HEAD,%f,%f,-0.16,%d,TAIL"%(x_a,Y_a,4)
                    byte_x = pack('f',a[0])
                    byte_y = pack('f',a[1])
                    byte_z = pack('f',-0.07)
               # data = ustruct.pack("bbbbbbbbbbbbbbb",0x24,byte_x[0],byte_x[1],byte_x[2],byte_x[3],byte_y[0],byte_y[1],byte_y[2],byte_y[3],byte_z[0],byte_z[1],byte_z[2],byte_z[3],(nearblob.classid())+1,0x23)
                    print(out_str)
                #print([ i for i in data])
                    uart.write(out_str)
            #time.sleep(1)
            try:
                img.draw_string(0, 200, "t:%dms" %(t), scale=2, color=(255, 0, 0))
                lcd.display(img)
            except Exception as e:
                print(e)

    except Exception as e:
        raise e
    finally:
        print("end");
        if not task is None:
            kpu.deinit(task)
if __name__ == "__main__":
    try:
        labels = ['strawberry']
        anchors = [2.25, 3.59, 2.31, 4.0, 3.61, 3.28, 2.66, 3.84, 3.69, 2.77]
        # main(anchors = anchors, labels=labels, model_addr=0x300000, lcd_rotation=0)
        main(anchors = anchors, labels=labels, model_addr="/sd/m.kmodel")
    except Exception as e:
        sys.print_exception(e)
        lcd_show_except(e)
    finally:
        gc.collect()
